In [2]:
# 1 Importamos las librerias que necesitamos
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) # Para ver todas las columnas

In [3]:
# 1.1 Importamos bank-additional (csv)
b_add = pd.read_csv('../Data/raw/bank-additional.csv', delimiter=',', index_col=0) # bank-additional.csv

# Importamos customer-details.xlsx (excel) con varias hojas
df_2012 = pd.read_excel('../Data/raw/customer-details.xlsx', sheet_name="2012")
df_2013 = pd.read_excel('../Data/raw/customer-details.xlsx', sheet_name="2013")
df_2014 = pd.read_excel('../Data/raw/customer-details.xlsx', sheet_name="2014")

# Convertimos las 3 hojas excel en un solo df
df_customer = pd.concat(objs=[df_2012, df_2013, df_2014], axis=0)
df_customer.drop(columns='Unnamed: 0', inplace=True) # Eliminamos la columna de indice incremental 'Unnamed: O'

In [4]:
# 2 Exploracion de los datos de los datasets en importados
# 2.0.1 Visualización previa de df_customer
df_customer.sample(2)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
14325,35488,1,1,2012-03-28,16,bcc99ead-34b2-426e-ad57-48cb7d87ae78
12299,120799,1,2,2012-07-18,6,f238cae8-ce76-4833-b795-e7b745756971

In [5]:
# 2.0.2 Visualización previa de b_add
b_add.sample(2)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
32115,32.0,blue-collar,MARRIED,basic.9y,0.0,1.0,1.0,cellular,157,1,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,313","5099,1",no,2-febrero-2018,26.880,-86.754,da0e9fc4-4f4d-4a18-946d-b578dde6f0f8
24413,46.0,admin.,DIVORCED,high.school,NaN,1.0,0.0,cellular,168,1,999,0,NONEXISTENT,-0.1,"93,2",-42,NaN,"5195,8",no,15-septiembre-2019,33.964,-99.182,da431f79-aa03-4b2f-9553-22bda19648cc

In [6]:
# 2.1 Tamaño y tipo de datos de b_add
print(f"{b_add.dtypes}, \n") # Vemos los tipos de datos de las columnas para hacer los cambios pertinentes
print(b_add.shape) # Tenemos 43 mil filas y 23 columnas

# Notas:
# En la limpieza vamos a cambiar columnas con valores 0 y 1 a un formato unificado 'yes' y 'no' comop en la columna 'y' en 
# Vamos a convertir a tipos de datos categoricos las columnas: 'default', 'housing', 'loan', 'poutcome', 'contact', 'job', 'marital', 'education'
# Float: 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed' ya que estan en str y son valores numericos con decimales
# Arreglaremos la columna fecha para que tenga formato adecuado y no sea string

age               float64
job                   str
marital               str
education             str
default           float64
housing           float64
loan              float64
contact               str
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome              str
emp.var.rate      float64
cons.price.idx        str
cons.conf.idx         str
euribor3m             str
nr.employed           str
y                     str
date                  str
latitude          float64
longitude         float64
id_                   str
dtype: object,

(43000, 23)

In [7]:
# 2.2 Tamaño y tipo de datos de df_customer
print(f"{df_customer.dtypes}, \n") # Vemos los tipos de datos de las columnas para hacer los cambios pertinentes
print(df_customer.shape) # Tenemos 43170 filas y 6 columnas

# Notas:
# Income: Cambiar a float

Income                        int64
Kidhome                       int64
Teenhome                      int64
Dt_Customer          datetime64[us]
NumWebVisitsMonth             int64
ID                              str
dtype: object,

(43170, 6)

In [8]:
# 3 Duplicados
# 3.1 Ver duplicados de b_add
print(f" Hay : {b_add['id_'].duplicated().sum()} duplicados")

# Estadisticas descriptivas
b_add.describe().T

 Hay : 0 duplicados

,count,mean,std,min,25%,50%,75%,max
age,37880.0,39.977112,10.437957,17.000,32.00000,38.0000,47.00000,98.000
default,34019.0,0.000088,0.009390,0.000,0.00000,0.0000,0.00000,1.000
housing,41974.0,0.535998,0.498708,0.000,0.00000,1.0000,1.00000,1.000
loan,41974.0,0.155620,0.362499,0.000,0.00000,0.0000,0.00000,1.000
duration,43000.0,257.739279,258.666033,0.000,102.00000,179.0000,319.00000,4918.000
campaign,43000.0,2.567233,2.772294,1.000,1.00000,2.0000,3.00000,56.000
pdays,43000.0,962.330953,187.260394,0.000,999.00000,999.0000,999.00000,999.000
previous,43000.0,0.174023,0.497366,0.000,0.00000,0.0000,0.00000,7.000
emp.var.rate,43000.0,0.077128,1.573898,-3.400,-1.80000,1.1000,1.40000,1.400
latitude,43000.0,36.856697,7.225948,24.396,30.61475,36.7610,43.11325,49.384
longitude,43000.0,-95.939067,16.752282,-124.997,-110.49425,-95.8995,-81.42775,-66.937

In [9]:
# 3.2 Ver duplicados de df_customer
print(f" Hay : {df_customer['ID'].duplicated().sum()} duplicados")

# Estadisticas descriptivas
df_customer.describe().T

 Hay : 0 duplicados

,count,mean,min,25%,50%,75%,max,std
Income,43170.0,93227.389622,5841.0,49608.0,93009.5,136740.5,180802.0,50498.181989
Kidhome,43170.0,1.004749,0.0,0.0,1.0,2.0,2.0,0.815996
Teenhome,43170.0,0.998633,0.0,0.0,1.0,2.0,2.0,0.816008
Dt_Customer,43170,2013-05-11 22:09:47.407922,2012-01-01 00:00:00,2012-07-16 00:00:00,2013-03-01 00:00:00,2014-03-28 00:00:00,2014-12-31 00:00:00,NaN
NumWebVisitsMonth,43170.0,16.59129,1.0,9.0,17.0,25.0,32.0,9.241769

In [17]:
# 4 Nulos
# 4.1 Ver nulos en b_add (Ver % de nulos sobre las 43 mil filas)
b_add.isnull().mean().sort_values(ascending=False).round(4)*100

# Podemos ver que columnas tienen mayor proporcion de nulos que necesitarán ser tratados

euribor3m         21.53
default           20.89
age               11.91
education          4.20
housing            2.39
loan               2.39
cons.price.idx     1.10
job                0.80
date               0.58
marital            0.20
contact            0.00
pdays              0.00
previous           0.00
campaign           0.00
duration           0.00
emp.var.rate       0.00
poutcome           0.00
nr.employed        0.00
cons.conf.idx      0.00
y                  0.00
latitude           0.00
longitude          0.00
id_                0.00
dtype: float64

In [11]:
# 4.1.1 Observación de nulos en categoricas
b_add.describe(include=['object', 'str', 'category']).T


# Conclusiones:
# (job, marital, education) -> podriamos cambiar 'nan' por 'unknown'
# default: hay 34019 datos, 34016 son no y el resto no sabemos. Por el momento cambiamos por 'unknown'
# (housing y loan) -> hay aproximadamente 1000 datos de 43 mil que no tenemos info. Para no sesgar cambiamos por 'unknown'

# Resultado: Vamos proceder a cambiar todas nuevas variables categoricas, añadiremos la categoria unknown y rellenaremos los nan por dicho valor
# De esta forma no sesgamos los datos, podemos analizar independientemente esa falta de informacion y trabajamos con lo que ya tenemos sin eliminar nada

                count unique                                   top   freq
job             42655     11                                admin.  10873
marital         42915      3                               MARRIED  25999
education       41193      7                     university.degree  12722
contact         43000      2                              cellular  27396
poutcome        43000      3                           NONEXISTENT  37103
cons.price.idx  42529     26                                93,994   7938
cons.conf.idx   43000     26                                 -36,4   8020
euribor3m       33744    309                                 4,857   2287
nr.employed     43000     11                                5228,1  16980
y               43000      2                                    no  38156
date            42752   1825                       28-febrero-2018     95
id_             43000  43000  089b39d8-e4d0-461b-87d4-814d71e0e079      1

In [12]:
# 4.1.2 Nulos en variables numericas
b_add[['age', 'cons.price.idx', 'euribor3m', 'date']].describe(include=['int', 'float', 'datetime']).T

## Age, podemos usar la mediana para los datos faltantes
## cons.price.idx y euribor3m: podrian ser datos que dependen de la fecha no podemos eliminarlo sin mas
## date: aunque sean pocas filas, vamos a conservarla para el merge

       count       mean        std   min   25%   50%   75%   max
age  37880.0  39.977112  10.437957  17.0  32.0  38.0  47.0  98.0

In [13]:
# 4.2 Nulos en df_customer
df_customer.info() # No tenemos nulos

<class 'pandas.DataFrame'>
Index: 43170 entries, 0 to 14089
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             43170 non-null  int64
 1   Kidhome            43170 non-null  int64
 2   Teenhome           43170 non-null  int64
 3   Dt_Customer        43170 non-null  datetime64[us]
 4   NumWebVisitsMonth  43170 non-null  int64
 5   ID                 43170 non-null  str
dtypes: datetime64[us](1), int64(4), str(1)
memory usage: 2.3 MB

In [ ]:
# 5 Consistencia en los datos
b_add[['y', 'loan', 'housing', 'default']].value_counts(dropna=False) # Tambien vemos que hay nulos

# Podemos ver como tenemos incosistencia en los valores de algunas columnas. Algunas columnas con valores 0 y 1
# y la columna 'y' con valores 'yes' o 'no', procedere a unificarlas en los valores 'yes' y 'no' en la limpieza

y    loan  housing  default
no   0.0   1.0      0.0        12877
           0.0      0.0        11522
           1.0      NaN         3582
           0.0      NaN         3441
     1.0   1.0      0.0         2700
yes  0.0   1.0      0.0         1997
no   1.0   0.0      0.0         1849
yes  0.0   0.0      0.0         1626
no   1.0   1.0      NaN          722
     NaN   NaN      0.0          692
     1.0   0.0      NaN          548
yes  1.0   1.0      0.0          387
           0.0      0.0          265
no   NaN   NaN      NaN          220
yes  0.0   0.0      NaN          199
           1.0      NaN          195
     NaN   NaN      0.0          101
     1.0   1.0      NaN           37
           0.0      NaN           24
     NaN   NaN      NaN           13
no   0.0   0.0      1.0            2
           1.0      1.0            1
Name: count, dtype: int64

In [15]:
# 6 Pasar los datos a la carpeta interim
b_add.to_csv('../Data/interim/b_add_interim.csv', index = False) # index = False para que no se cree columna "Unnamed: 0"
df_customer.to_csv('../Data/interim/df_customer_interim.csv', index = False)